vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    skills_manager:
      uri_prefix: /Portfolio/Skills
      upload_destination: "%kernel.project_dir%/public/build/Portfolio/Skills"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    projects_manager:
      uri_prefix: /Portfolio/myjob
      upload_destination: "%kernel.project_dir%/public/build/Portfolio/myjob"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
