vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    post_thumnail:
      uri_prefix: /Portfolio/
      upload_destination: "%kernel.project_dir%/public/Portfolio"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
