version: '3'

services:
    app:
        container_name: portfolio-app
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8000:8000
        
        volumes:
            - ./app/:/var/www/
        networks:
            - portfolio

    database:
        container_name: portfolio-database
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: portfolio
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - portfolio

    phpmyadmin:
        container_name: portfolio-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - 3001:80
        environment:
            - PMA_HOST=database
        networks:
            - portfolio

volumes:
    db-data:

networks:
    portfolio:
